### ISSUE TITLE
Blow-up pane option

### ISSUE THREAD

**Issue by michaelpb** [michaelpb/whiteboard#16]
- Simpler solution to "whiteboard" annotations: Like shutter, select an
     area of the screen to create a blowup (creates and saves a png image).
      This allows for parts of the presentation to be focused on, and
      annotated, and the annotations to be "returnable", e.g. one important
      part of code or a website could be blown up and then diagrammed.

**Subtasks:**
- [ ] Blowups can be created (selecting screen area)
- [ ] Blowups are stored in a top-level "blowups" editor (at the same level as slides)
- [ ] A slide-editor like interface can drop in from the right to select blow ups
- [ ] They can be viewed and drawn on (1 simple marker for now)

```
[blowup]
background = _wb_blowups/01_fg.png
foreground = _wb_blowups/01_bg.png
```

**More notes:**

- Route 1: Have "side deck" of slides
    - alternate = true
    - Blow-up tool automatically makes a side slide that contains 1 pane:
        - Drawable image pane
        - image-canvas = ./blowups/whatever.png
- Route 2: Make all slides drawable
